### ISSUE TITLE
remove gnode dependency

### ISSUE THREAD

**Issue by Raynos** [Gozala/channel#1]
Calling `gnode` directly is just as bad as calling `coffee-script` directly.

It mutates the `require.extensions` global.

You can move `gnode` to devDependencies.

**Comment by Gozala** [comment]
Note that gnode is only pulled in if you call spawn, otherwise it isn't so I don't think that is such big of a deal. Also `gnode` does nothing if node has generators.

**Comment by Gozala** [comment]
Here is a relevant lines of code:
https://github.com/Gozala/channel/blob/master/index.js#L16-L20

**Comment by Raynos** [comment]
@Gozala 
- I still have to install all of `esprima` when I want to install channel
- this cannot be browserified cleanly because it depends on gnode & esprima and will generate a huge bundle.

`spawn` should not have any opinions about `gnode`. What if I want to use my own alternative generators compiler ?

**Comment by Gozala** [comment]
Yeah that argument, makes sense to me. I'll move gnode to a devDependencies, although now I'm not sure how does testling going to run my spawn tests :(

**Comment by Gozala** [comment]
Fixed!
